export declare function chunkHexBytes(str: string): any[];
export declare function bytesToInt(bytes: number[]): number;
export declare function hexToBytes(hex: string): number[];
export declare function bytesToHex(bytes: number[]): string;
export declare function intToHex(n: number, length?: number, padwith?: string): string;
export declare function intToBytes(n: number, length?: number, padwith?: number): number[];
export declare function asciiHexToString(hex: string): string;
export declare function asciiBytesToString(bytes: number[]): string;
export declare function stringToAsciiHex(s: string): string;
export declare function stringToAsciiBytes(s: string): number[];
